###########################
######### 生产模式
##########################
spring:
  # 环境 dev|test|prod
  profiles:
    active: dev
  cache:
    type: redis
  redis:
    host: 192.168.233.137
    port: 6379
    password:
    pool:
      max-active: 10  # 连接池最大连接数（使用负值表示没有限制）
      max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 8       # 连接池中的最大空闲连接
      min-idle: 0       # 连接池中的最小空闲连接


#########################
######## mybatis
#########################
mybatis:
  type-aliases-package: com.qiang.modules.sys.pojo
  mapper-locations: classpath:mapping/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl





